import type { TesseraPreIpoAsset } from "../sdk/constants";
import { getOfficialEquityLogo } from "./assetLogos";

// Fixtures for explicitly selected local simulation only; never a verified catalog.
export const DEMO_EQUITIES: TesseraPreIpoAsset[] = [
  {
    symbol: "$TSPACEX",
    ticker: "TSPACEX",
    name: "SpaceX",
    mintAddress: "DiKVjAz8vGALzLwoZz7PPxUTnDsTVyF7GNx9F3BxVYEs",
    issuer: "Tessera Private Equity",
    custodian: "Fireblocks Institutional Custody",
    legalFramework: "Cayman Islands SPC - Loan Participation Right",
    proofOfReserve: "Pyth Network Oracle / On-Chain PoR",
    meteoraPoolAddress: "METspcxPoolAddress1111111111111111111111111",
    logoUrl: getOfficialEquityLogo("SPACEX"),
    currentStockPriceUsd: 215.4,
    isPreIpo: true,
  },
  {
    symbol: "$TOPAI",
    ticker: "TOPAI",
    name: "OpenAI",
    mintAddress: "3PFKgvU4P8hcuW1X2VjAgRHNsz1TnA4SLyjEDNfhzLC7",
    issuer: "Tessera Private Equity",
    custodian: "Fireblocks Institutional Custody",
    legalFramework: "Cayman Islands SPC - Loan Participation Right",
    proofOfReserve: "Pyth Network Oracle / On-Chain PoR",
    meteoraPoolAddress: "METopeNAIPoolAddress111111111111111111111111",
    logoUrl: getOfficialEquityLogo("OPENAI"),
    currentStockPriceUsd: 185.0,
    isPreIpo: true,
  },
  {
    symbol: "$TSTRIPE",
    ticker: "TSTRIPE",
    name: "Stripe",
    mintAddress: "HjSo935gqYjDaHLMga5SRfkiACjCX5wE3ZnbQpDoqWGb",
    issuer: "Tessera Private Equity",
    custodian: "Fireblocks Institutional Custody",
    legalFramework: "Cayman Islands SPC - Loan Participation Right",
    proofOfReserve: "Pyth Network Oracle / On-Chain PoR",
    meteoraPoolAddress: "METstripePoolAddress111111111111111111111111",
    logoUrl: getOfficialEquityLogo("STRIPE"),
    currentStockPriceUsd: 72.5,
    isPreIpo: true,
  },
  {
    symbol: "$NVDA",
    ticker: "NVDA",
    name: "NVIDIA",
    mintAddress: "BpWrd7wGZaS3TTM8Nitk3cHHf91HAE2QWVk2E5dwBqKb",
    issuer: "Backpack Securities",
    custodian: "Fireblocks Institutional Custody",
    legalFramework: "New York UCC Article 8 Securities Intermediary",
    proofOfReserve: "Pyth Network Oracle / On-Chain PoR",
    meteoraPoolAddress: "METnvdaPoolAddress1111111111111111111111111",
    logoUrl: getOfficialEquityLogo("NVDA"),
    currentStockPriceUsd: 128.5,
    isPreIpo: false,
  },
  {
    symbol: "$TSLA",
    ticker: "TSLA",
    name: "Tesla",
    mintAddress: "TSLA111111111111111111111111111111111111111",
    issuer: "Backpack Securities",
    custodian: "Fireblocks Institutional Custody",
    legalFramework: "New York UCC Article 8 Securities Intermediary",
    proofOfReserve: "Pyth Network Oracle / On-Chain PoR",
    meteoraPoolAddress: "METtslaPoolAddress1111111111111111111111111",
    logoUrl: getOfficialEquityLogo("TSLA"),
    currentStockPriceUsd: 245.2,
    isPreIpo: false,
  },
];

// Backward-compatible alias for existing UI components
export type TokenizedEquity = TesseraPreIpoAsset;
export const DEMO_TOKENIZED_EQUITIES = DEMO_EQUITIES;
